name: Java CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io/  -Dsonar.login=420aa028944986a7c323bd3ff2cecb159217cf8f -Dsonar.organization=duyluonganh
